"use client"
import { store } from "@/components/redux/store";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Quiz App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-screen grid grid-cols-1 grid-rows-1 bg-quiz-pink p-2 md:p-4`}
        suppressHydrationWarning={true}
      >
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
